name: Local Build

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  REGISTRY: local

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - 'main'

jobs:
  p4c_image:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3.4.0
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Build and export
       uses: docker/build-push-action@v4
       with:
         context: .
         file: p4.dockerfile
         outputs: type=docker,dest=/tmp/p4.tar
         tags: ${{ env.REGISTRY }}/p4:${{ env.BRANCH_NAME }}
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: p4
         path: /tmp/p4.tar

  grpc_image:
    needs: p4c_image
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3.4.0
     # https://github.com/docker/setup-buildx-action
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
         name: p4
         path: /tmp
     - name: Load image
       run: |
         docker load --input /tmp/p4.tar
         docker image ls -a
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
       with:
        driver: docker
     - name: Build and export
       uses: docker/build-push-action@v4
       with:
         context: .
         file: grpc.dockerfile
         push: false
         load: true
         tags: ${{ env.REGISTRY }}/grpc:${{ env.BRANCH_NAME }}
         build-args: |
           image=${{ env.REGISTRY }}/p4:${{ env.BRANCH_NAME }}
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: p4
         path: /tmp/grpc.tar

  bmv_image:
    needs: grpc_image
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3.4.0
     # https://github.com/docker/setup-buildx-action
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
         name: p4
         path: /tmp
     - name: Load image
       run: |
         docker load --input /tmp/grpc.tar
         docker image ls -a
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Build and export
       uses: docker/build-push-action@v4
       with:
         context: .
         file: bmv.dockerfile
         push: false
         load: true
         tags: ${{ env.REGISTRY }}/bmv:${{ env.BRANCH_NAME }}
         build-args: |
           image=${{ env.REGISTRY }}/grpc:${{ env.BRANCH_NAME }}

     - name: List images
       run: docker image ls -a
